<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class KabupatenKotaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('kabupaten_kota')->insert([
            ["kode_kab_kota" => "1101", "kab_kota" => "Kabupaten Aceh Selatan", "kode_provinsi" => "11", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1102", "kab_kota" => "Kabupaten Aceh Tenggara", "kode_provinsi" => "11", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1103", "kab_kota" => "Kabupaten Aceh Timur", "kode_provinsi" => "11", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1104", "kab_kota" => "Kabupaten Aceh Tengah", "kode_provinsi" => "11", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1105", "kab_kota" => "Kabupaten Aceh Barat", "kode_provinsi" => "11", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1106", "kab_kota" => "Kabupaten Aceh Besar", "kode_provinsi" => "11", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1107", "kab_kota" => "Kabupaten Pidie", "kode_provinsi" => "11", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1108", "kab_kota" => "Kabupaten Aceh Utara", "kode_provinsi" => "11", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1109", "kab_kota" => "Kabupaten Simeulue", "kode_provinsi" => "11", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1110", "kab_kota" => "Kabupaten Aceh Singkil", "kode_provinsi" => "11", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1111", "kab_kota" => "Kabupaten Bireuen", "kode_provinsi" => "11", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1112", "kab_kota" => "Kabupaten Aceh Barat Daya", "kode_provinsi" => "11", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1113", "kab_kota" => "Kabupaten Gayo Lues", "kode_provinsi" => "11", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1114", "kab_kota" => "Kabupaten Aceh Jaya", "kode_provinsi" => "11", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1115", "kab_kota" => "Kabupaten Nagan Raya", "kode_provinsi" => "11", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1116", "kab_kota" => "Kabupaten Aceh Tamiang", "kode_provinsi" => "11", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1117", "kab_kota" => "Kabupaten Bener Meriah", "kode_provinsi" => "11", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1118", "kab_kota" => "Kabupaten Pidie Jaya", "kode_provinsi" => "11", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1171", "kab_kota" => "Kota Banda Aceh", "kode_provinsi" => "11", "is_ibu_kota" => 1, "aktif" => 1],
            ["kode_kab_kota" => "1172", "kab_kota" => "Kota Sabang", "kode_provinsi" => "11", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1173", "kab_kota" => "Kota Lhokseumawe", "kode_provinsi" => "11", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1174", "kab_kota" => "Kota Langsa", "kode_provinsi" => "11", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1175", "kab_kota" => "Kota Subulussalam", "kode_provinsi" => "11", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1201", "kab_kota" => "Kabupaten Tapanuli Tengah", "kode_provinsi" => "12", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1202", "kab_kota" => "Kabupaten Tapanuli Utara", "kode_provinsi" => "12", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1203", "kab_kota" => "Kabupaten Tapanuli Selatan", "kode_provinsi" => "12", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1204", "kab_kota" => "Kabupaten Nias", "kode_provinsi" => "12", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1205", "kab_kota" => "Kabupaten Langkat", "kode_provinsi" => "12", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1206", "kab_kota" => "Kabupaten Karo", "kode_provinsi" => "12", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1207", "kab_kota" => "Kabupaten Deli Serdang", "kode_provinsi" => "12", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1208", "kab_kota" => "Kabupaten Simalungun", "kode_provinsi" => "12", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1209", "kab_kota" => "Kabupaten Asahan", "kode_provinsi" => "12", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1210", "kab_kota" => "Kabupaten Labuhanbatu", "kode_provinsi" => "12", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1211", "kab_kota" => "Kabupaten Dairi", "kode_provinsi" => "12", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1212", "kab_kota" => "Kabupaten Toba Samosir", "kode_provinsi" => "12", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1213", "kab_kota" => "Kabupaten Mandailing Natal", "kode_provinsi" => "12", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1214", "kab_kota" => "Kabupaten Nias Selatan", "kode_provinsi" => "12", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1215", "kab_kota" => "Kabupaten Pakpak Bharat", "kode_provinsi" => "12", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1216", "kab_kota" => "Kabupaten Humbang Hasundutan", "kode_provinsi" => "12", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1217", "kab_kota" => "Kabupaten Samosir", "kode_provinsi" => "12", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1218", "kab_kota" => "Kabupaten Serdang Bedagai", "kode_provinsi" => "12", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1219", "kab_kota" => "Kabupaten Batu Bara", "kode_provinsi" => "12", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1220", "kab_kota" => "Kabupaten Padang Lawas Utara", "kode_provinsi" => "12", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1221", "kab_kota" => "Kabupaten Padang Lawas", "kode_provinsi" => "12", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1222", "kab_kota" => "Kabupaten Labuhanbatu Selatan", "kode_provinsi" => "12", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1223", "kab_kota" => "Kabupaten Labuhanbatu Utara", "kode_provinsi" => "12", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1224", "kab_kota" => "Kabupaten Nias Utara", "kode_provinsi" => "12", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1225", "kab_kota" => "Kabupaten Nias Barat", "kode_provinsi" => "12", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1271", "kab_kota" => "Kota Medan", "kode_provinsi" => "12", "is_ibu_kota" => 1, "aktif" => 1],
            ["kode_kab_kota" => "1272", "kab_kota" => "Kota Pematangsiantar", "kode_provinsi" => "12", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1273", "kab_kota" => "Kota Sibolga", "kode_provinsi" => "12", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1274", "kab_kota" => "Kota Tanjung Balai", "kode_provinsi" => "12", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1275", "kab_kota" => "Kota Binjai", "kode_provinsi" => "12", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1276", "kab_kota" => "Kota Tebing Tinggi", "kode_provinsi" => "12", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1277", "kab_kota" => "Kota Padang Sidempuan", "kode_provinsi" => "12", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1278", "kab_kota" => "Kota Gunungsitoli", "kode_provinsi" => "12", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1301", "kab_kota" => "Kabupaten Pesisir Selatan", "kode_provinsi" => "13", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1302", "kab_kota" => "Kabupaten Solok", "kode_provinsi" => "13", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1303", "kab_kota" => "Kabupaten Sijunjung", "kode_provinsi" => "13", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1304", "kab_kota" => "Kabupaten Tanah Datar", "kode_provinsi" => "13", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1305", "kab_kota" => "Kabupaten Padang Pariaman", "kode_provinsi" => "13", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1306", "kab_kota" => "Kabupaten Agam", "kode_provinsi" => "13", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1307", "kab_kota" => "Kabupaten Lima Puluh Kota", "kode_provinsi" => "13", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1308", "kab_kota" => "Kabupaten Pasaman", "kode_provinsi" => "13", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1309", "kab_kota" => "Kabupaten Kepulauan Mentawai", "kode_provinsi" => "13", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1310", "kab_kota" => "Kabupaten Dharmasraya", "kode_provinsi" => "13", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1311", "kab_kota" => "Kabupaten Solok Selatan", "kode_provinsi" => "13", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1312", "kab_kota" => "Kabupaten Pasaman Barat", "kode_provinsi" => "13", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1371", "kab_kota" => "Kota Padang", "kode_provinsi" => "13", "is_ibu_kota" => 1, "aktif" => 1],
            ["kode_kab_kota" => "1372", "kab_kota" => "Kota Solok", "kode_provinsi" => "13", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1373", "kab_kota" => "Kota Sawahlunto", "kode_provinsi" => "13", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1374", "kab_kota" => "Kota Padang Panjang", "kode_provinsi" => "13", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1375", "kab_kota" => "Kota Bukittinggi", "kode_provinsi" => "13", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1376", "kab_kota" => "Kota Payakumbuh", "kode_provinsi" => "13", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1377", "kab_kota" => "Kota Pariaman", "kode_provinsi" => "13", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1401", "kab_kota" => "Kabupaten Kampar", "kode_provinsi" => "14", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1402", "kab_kota" => "Kabupaten Indragiri Hulu", "kode_provinsi" => "14", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1403", "kab_kota" => "Kabupaten Bengkalis", "kode_provinsi" => "14", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1404", "kab_kota" => "Kabupaten Indragiri Hilir", "kode_provinsi" => "14", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1405", "kab_kota" => "Kabupaten Pelalawan", "kode_provinsi" => "14", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1406", "kab_kota" => "Kabupaten Rokan Hulu", "kode_provinsi" => "14", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1407", "kab_kota" => "Kabupaten Rokan Hilir", "kode_provinsi" => "14", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1408", "kab_kota" => "Kabupaten Siak", "kode_provinsi" => "14", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1409", "kab_kota" => "Kabupaten Kuantan Singingi", "kode_provinsi" => "14", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1410", "kab_kota" => "Kabupaten Kepulauan Meranti", "kode_provinsi" => "14", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1471", "kab_kota" => "Kota Pekanbaru", "kode_provinsi" => "14", "is_ibu_kota" => 1, "aktif" => 1],
            ["kode_kab_kota" => "1472", "kab_kota" => "Kota Dumai", "kode_provinsi" => "14", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1501", "kab_kota" => "Kabupaten Kerinci", "kode_provinsi" => "15", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1502", "kab_kota" => "Kabupaten Merangin", "kode_provinsi" => "15", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1503", "kab_kota" => "Kabupaten Sarolangun", "kode_provinsi" => "15", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1504", "kab_kota" => "Kabupaten Batanghari", "kode_provinsi" => "15", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1505", "kab_kota" => "Kabupaten Muaro Jambi", "kode_provinsi" => "15", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1506", "kab_kota" => "Kabupaten Tanjung Jabung Barat", "kode_provinsi" => "15", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1507", "kab_kota" => "Kabupaten Tanjung Jabung Timur", "kode_provinsi" => "15", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1508", "kab_kota" => "Kabupaten Bungo", "kode_provinsi" => "15", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1509", "kab_kota" => "Kabupaten Tebo", "kode_provinsi" => "15", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1571", "kab_kota" => "Kota Jambi", "kode_provinsi" => "15", "is_ibu_kota" => 1, "aktif" => 1],
            ["kode_kab_kota" => "1572", "kab_kota" => "Kota Sungai Penuh", "kode_provinsi" => "15", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1601", "kab_kota" => "Kabupaten Ogan Komering Ulu", "kode_provinsi" => "16", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1602", "kab_kota" => "Kabupaten Ogan Komering Ilir", "kode_provinsi" => "16", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1603", "kab_kota" => "Kabupaten Muara Enim", "kode_provinsi" => "16", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1604", "kab_kota" => "Kabupaten Lahat", "kode_provinsi" => "16", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1605", "kab_kota" => "Kabupaten Musi Rawas", "kode_provinsi" => "16", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1606", "kab_kota" => "Kabupaten Musi Banyuasin", "kode_provinsi" => "16", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1607", "kab_kota" => "Kabupaten Banyuasin", "kode_provinsi" => "16", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1608", "kab_kota" => "Kabupaten Ogan Komering Ulu Timur", "kode_provinsi" => "16", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1609", "kab_kota" => "Kabupaten Ogan Komering Ulu Selatan", "kode_provinsi" => "16", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1610", "kab_kota" => "Kabupaten Ogan Ilir", "kode_provinsi" => "16", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1611", "kab_kota" => "Kabupaten Empat Lawang", "kode_provinsi" => "16", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1612", "kab_kota" => "Kabupaten Penukal Abab Lematang Ilir", "kode_provinsi" => "16", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1613", "kab_kota" => "Kabupaten Musi Rawas Utara", "kode_provinsi" => "16", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1671", "kab_kota" => "Kota Palembang", "kode_provinsi" => "16", "is_ibu_kota" => 1, "aktif" => 1],
            ["kode_kab_kota" => "1672", "kab_kota" => "Kota Pagar Alam", "kode_provinsi" => "16", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1673", "kab_kota" => "Kota Lubuk Linggau", "kode_provinsi" => "16", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1674", "kab_kota" => "Kota Prabumulih", "kode_provinsi" => "16", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1701", "kab_kota" => "Kabupaten Bengkulu Selatan", "kode_provinsi" => "17", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1702", "kab_kota" => "Kabupaten Rejang Lebong", "kode_provinsi" => "17", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1703", "kab_kota" => "Kabupaten Bengkulu Utara", "kode_provinsi" => "17", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1704", "kab_kota" => "Kabupaten Kaur", "kode_provinsi" => "17", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1705", "kab_kota" => "Kabupaten Seluma", "kode_provinsi" => "17", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1706", "kab_kota" => "Kabupaten Muko Muko", "kode_provinsi" => "17", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1707", "kab_kota" => "Kabupaten Lebong", "kode_provinsi" => "17", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1708", "kab_kota" => "Kabupaten Kepahiang", "kode_provinsi" => "17", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1709", "kab_kota" => "Kabupaten Bengkulu Tengah", "kode_provinsi" => "17", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1771", "kab_kota" => "Kota Bengkulu", "kode_provinsi" => "17", "is_ibu_kota" => 1, "aktif" => 1],
            ["kode_kab_kota" => "1801", "kab_kota" => "Kabupaten Lampung Selatan", "kode_provinsi" => "18", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1802", "kab_kota" => "Kabupaten Lampung Tengah", "kode_provinsi" => "18", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1803", "kab_kota" => "Kabupaten Lampung Utara", "kode_provinsi" => "18", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1804", "kab_kota" => "Kabupaten Lampung Barat", "kode_provinsi" => "18", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1805", "kab_kota" => "Kabupaten Tulang Bawang", "kode_provinsi" => "18", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1806", "kab_kota" => "Kabupaten Tanggamus", "kode_provinsi" => "18", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1807", "kab_kota" => "Kabupaten Lampung Timur", "kode_provinsi" => "18", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1808", "kab_kota" => "Kabupaten Way Kanan", "kode_provinsi" => "18", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1809", "kab_kota" => "Kabupaten Pesawaran", "kode_provinsi" => "18", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1810", "kab_kota" => "Kabupaten Pringsewu", "kode_provinsi" => "18", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1811", "kab_kota" => "Kabupaten Mesuji", "kode_provinsi" => "18", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1812", "kab_kota" => "Kabupaten Tulang Bawang Barat", "kode_provinsi" => "18", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1813", "kab_kota" => "Kabupaten Pesisir Barat", "kode_provinsi" => "18", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1871", "kab_kota" => "Kota Bandar Lampung", "kode_provinsi" => "18", "is_ibu_kota" => 1, "aktif" => 1],
            ["kode_kab_kota" => "1872", "kab_kota" => "Kota Metro", "kode_provinsi" => "18", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1901", "kab_kota" => "Kabupaten Bangka", "kode_provinsi" => "19", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1902", "kab_kota" => "Kabupaten Belitung", "kode_provinsi" => "19", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1903", "kab_kota" => "Kabupaten Bangka Selatan", "kode_provinsi" => "19", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1904", "kab_kota" => "Kabupaten Bangka Tengah", "kode_provinsi" => "19", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1905", "kab_kota" => "Kabupaten Bangka Barat", "kode_provinsi" => "19", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1906", "kab_kota" => "Kabupaten Belitung Timur", "kode_provinsi" => "19", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "1971", "kab_kota" => "Kota Pangkal Pinang", "kode_provinsi" => "19", "is_ibu_kota" => 1, "aktif" => 1],
            ["kode_kab_kota" => "2101", "kab_kota" => "Kabupaten Bintan", "kode_provinsi" => "21", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "2102", "kab_kota" => "Kabupaten Karimun", "kode_provinsi" => "21", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "2103", "kab_kota" => "Kabupaten Natuna", "kode_provinsi" => "21", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "2104", "kab_kota" => "Kabupaten Lingga", "kode_provinsi" => "21", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "2105", "kab_kota" => "Kabupaten Kepulauan Anambas", "kode_provinsi" => "21", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "2171", "kab_kota" => "Kota Batam", "kode_provinsi" => "21", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "2172", "kab_kota" => "Kota Tanjung Pinang", "kode_provinsi" => "21", "is_ibu_kota" => 1, "aktif" => 1],
            ["kode_kab_kota" => "3101", "kab_kota" => "Kabupaten Administrasi Kepulauan Seribu", "kode_provinsi" => "31", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3171", "kab_kota" => "Kota Administrasi Jakarta Pusat", "kode_provinsi" => "31", "is_ibu_kota" => 1, "aktif" => 1],
            ["kode_kab_kota" => "3172", "kab_kota" => "Kota Administrasi Jakarta Utara", "kode_provinsi" => "31", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3173", "kab_kota" => "Kota Administrasi Jakarta Barat", "kode_provinsi" => "31", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3174", "kab_kota" => "Kota Administrasi Jakarta Selatan", "kode_provinsi" => "31", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3175", "kab_kota" => "Kota Administrasi Jakarta Timur", "kode_provinsi" => "31", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3201", "kab_kota" => "Kabupaten Bogor", "kode_provinsi" => "32", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3202", "kab_kota" => "Kabupaten Sukabumi", "kode_provinsi" => "32", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3203", "kab_kota" => "Kabupaten Cianjur", "kode_provinsi" => "32", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3204", "kab_kota" => "Kabupaten Bandung", "kode_provinsi" => "32", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3205", "kab_kota" => "Kabupaten Garut", "kode_provinsi" => "32", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3206", "kab_kota" => "Kabupaten Tasikmalaya", "kode_provinsi" => "32", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3207", "kab_kota" => "Kabupaten Ciamis", "kode_provinsi" => "32", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3208", "kab_kota" => "Kabupaten Kuningan", "kode_provinsi" => "32", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3209", "kab_kota" => "Kabupaten Cirebon", "kode_provinsi" => "32", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3210", "kab_kota" => "Kabupaten Majalengka", "kode_provinsi" => "32", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3211", "kab_kota" => "Kabupaten Sumedang", "kode_provinsi" => "32", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3212", "kab_kota" => "Kabupaten Indramayu", "kode_provinsi" => "32", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3213", "kab_kota" => "Kabupaten Subang", "kode_provinsi" => "32", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3214", "kab_kota" => "Kabupaten Purwakarta", "kode_provinsi" => "32", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3215", "kab_kota" => "Kabupaten Karawang", "kode_provinsi" => "32", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3216", "kab_kota" => "Kabupaten Bekasi", "kode_provinsi" => "32", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3217", "kab_kota" => "Kabupaten Bandung Barat", "kode_provinsi" => "32", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3218", "kab_kota" => "Kabupaten Pangandaran", "kode_provinsi" => "32", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3271", "kab_kota" => "Kota Bogor", "kode_provinsi" => "32", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3272", "kab_kota" => "Kota Sukabumi", "kode_provinsi" => "32", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3273", "kab_kota" => "Kota Bandung", "kode_provinsi" => "32", "is_ibu_kota" => 1, "aktif" => 1],
            ["kode_kab_kota" => "3274", "kab_kota" => "Kota Cirebon", "kode_provinsi" => "32", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3275", "kab_kota" => "Kota Bekasi", "kode_provinsi" => "32", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3276", "kab_kota" => "Kota Depok", "kode_provinsi" => "32", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3277", "kab_kota" => "Kota Cimahi", "kode_provinsi" => "32", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3278", "kab_kota" => "Kota Tasikmalaya", "kode_provinsi" => "32", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3279", "kab_kota" => "Kota Banjar", "kode_provinsi" => "32", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3301", "kab_kota" => "Kabupaten Cilacap", "kode_provinsi" => "33", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3302", "kab_kota" => "Kabupaten Banyumas", "kode_provinsi" => "33", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3303", "kab_kota" => "Kabupaten Purbalingga", "kode_provinsi" => "33", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3304", "kab_kota" => "Kabupaten Banjarnegara", "kode_provinsi" => "33", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3305", "kab_kota" => "Kabupaten Kebumen", "kode_provinsi" => "33", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3306", "kab_kota" => "Kabupaten Purworejo", "kode_provinsi" => "33", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3307", "kab_kota" => "Kabupaten Wonosobo", "kode_provinsi" => "33", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3308", "kab_kota" => "Kabupaten Magelang", "kode_provinsi" => "33", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3309", "kab_kota" => "Kabupaten Boyolali", "kode_provinsi" => "33", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3310", "kab_kota" => "Kabupaten Klaten", "kode_provinsi" => "33", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3311", "kab_kota" => "Kabupaten Sukoharjo", "kode_provinsi" => "33", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3312", "kab_kota" => "Kabupaten Wonogiri", "kode_provinsi" => "33", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3313", "kab_kota" => "Kabupaten Karanganyar", "kode_provinsi" => "33", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3314", "kab_kota" => "Kabupaten Sragen", "kode_provinsi" => "33", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3315", "kab_kota" => "Kabupaten Grobogan", "kode_provinsi" => "33", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3316", "kab_kota" => "Kabupaten Blora", "kode_provinsi" => "33", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3317", "kab_kota" => "Kabupaten Rembang", "kode_provinsi" => "33", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3318", "kab_kota" => "Kabupaten Pati", "kode_provinsi" => "33", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3319", "kab_kota" => "Kabupaten Kudus", "kode_provinsi" => "33", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3320", "kab_kota" => "Kabupaten Jepara", "kode_provinsi" => "33", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3321", "kab_kota" => "Kabupaten Demak", "kode_provinsi" => "33", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3322", "kab_kota" => "Kabupaten Semarang", "kode_provinsi" => "33", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3323", "kab_kota" => "Kabupaten Temanggung", "kode_provinsi" => "33", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3324", "kab_kota" => "Kabupaten Kendal", "kode_provinsi" => "33", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3325", "kab_kota" => "Kabupaten Batang", "kode_provinsi" => "33", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3326", "kab_kota" => "Kabupaten Pekalongan", "kode_provinsi" => "33", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3327", "kab_kota" => "Kabupaten Pemalang", "kode_provinsi" => "33", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3328", "kab_kota" => "Kabupaten Tegal", "kode_provinsi" => "33", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3329", "kab_kota" => "Kabupaten Brebes", "kode_provinsi" => "33", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3371", "kab_kota" => "Kota Magelang", "kode_provinsi" => "33", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3372", "kab_kota" => "Kota Surakarta", "kode_provinsi" => "33", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3373", "kab_kota" => "Kota Salatiga", "kode_provinsi" => "33", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3374", "kab_kota" => "Kota Semarang", "kode_provinsi" => "33", "is_ibu_kota" => 1, "aktif" => 1],
            ["kode_kab_kota" => "3375", "kab_kota" => "Kota Pekalongan", "kode_provinsi" => "33", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3376", "kab_kota" => "Kota Tegal", "kode_provinsi" => "33", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3401", "kab_kota" => "Kabupaten Kulon Progo", "kode_provinsi" => "34", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3402", "kab_kota" => "Kabupaten Bantul", "kode_provinsi" => "34", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3403", "kab_kota" => "Kabupaten Gunungkidul", "kode_provinsi" => "34", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3404", "kab_kota" => "Kabupaten Sleman", "kode_provinsi" => "34", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3471", "kab_kota" => "Kota Yogyakarta", "kode_provinsi" => "34", "is_ibu_kota" => 1, "aktif" => 1],
            ["kode_kab_kota" => "3501", "kab_kota" => "Kabupaten Pacitan", "kode_provinsi" => "35", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3502", "kab_kota" => "Kabupaten Ponorogo", "kode_provinsi" => "35", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3503", "kab_kota" => "Kabupaten Trenggalek", "kode_provinsi" => "35", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3504", "kab_kota" => "Kabupaten Tulungagung", "kode_provinsi" => "35", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3505", "kab_kota" => "Kabupaten Blitar", "kode_provinsi" => "35", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3506", "kab_kota" => "Kabupaten Kediri", "kode_provinsi" => "35", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3507", "kab_kota" => "Kabupaten Malang", "kode_provinsi" => "35", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3508", "kab_kota" => "Kabupaten Lumajang", "kode_provinsi" => "35", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3509", "kab_kota" => "Kabupaten Jember", "kode_provinsi" => "35", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3510", "kab_kota" => "Kabupaten Banyuwangi", "kode_provinsi" => "35", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3511", "kab_kota" => "Kabupaten Bondowoso", "kode_provinsi" => "35", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3512", "kab_kota" => "Kabupaten Situbondo", "kode_provinsi" => "35", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3513", "kab_kota" => "Kabupaten Probolinggo", "kode_provinsi" => "35", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3514", "kab_kota" => "Kabupaten Pasuruan", "kode_provinsi" => "35", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3515", "kab_kota" => "Kabupaten Sidoarjo", "kode_provinsi" => "35", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3516", "kab_kota" => "Kabupaten Mojokerto", "kode_provinsi" => "35", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3517", "kab_kota" => "Kabupaten Jombang", "kode_provinsi" => "35", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3518", "kab_kota" => "Kabupaten Nganjuk", "kode_provinsi" => "35", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3519", "kab_kota" => "Kabupaten Madiun", "kode_provinsi" => "35", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3520", "kab_kota" => "Kabupaten Magetan", "kode_provinsi" => "35", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3521", "kab_kota" => "Kabupaten Ngawi", "kode_provinsi" => "35", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3522", "kab_kota" => "Kabupaten Bojonegoro", "kode_provinsi" => "35", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3523", "kab_kota" => "Kabupaten Tuban", "kode_provinsi" => "35", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3524", "kab_kota" => "Kabupaten Lamongan", "kode_provinsi" => "35", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3525", "kab_kota" => "Kabupaten Gresik", "kode_provinsi" => "35", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3526", "kab_kota" => "Kabupaten Bangkalan", "kode_provinsi" => "35", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3527", "kab_kota" => "Kabupaten Sampang", "kode_provinsi" => "35", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3528", "kab_kota" => "Kabupaten Pamekasan", "kode_provinsi" => "35", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3529", "kab_kota" => "Kabupaten Sumenep", "kode_provinsi" => "35", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3571", "kab_kota" => "Kota Kediri", "kode_provinsi" => "35", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3572", "kab_kota" => "Kota Blitar", "kode_provinsi" => "35", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3573", "kab_kota" => "Kota Malang", "kode_provinsi" => "35", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3574", "kab_kota" => "Kota Probolinggo", "kode_provinsi" => "35", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3575", "kab_kota" => "Kota Pasuruan", "kode_provinsi" => "35", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3576", "kab_kota" => "Kota Mojokerto", "kode_provinsi" => "35", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3577", "kab_kota" => "Kota Madiun", "kode_provinsi" => "35", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3578", "kab_kota" => "Kota Surabaya", "kode_provinsi" => "35", "is_ibu_kota" => 1, "aktif" => 1],
            ["kode_kab_kota" => "3579", "kab_kota" => "Kota Batu", "kode_provinsi" => "35", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3601", "kab_kota" => "Kabupaten Pandeglang", "kode_provinsi" => "36", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3602", "kab_kota" => "Kabupaten Lebak", "kode_provinsi" => "36", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3603", "kab_kota" => "Kabupaten Tangerang", "kode_provinsi" => "36", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3604", "kab_kota" => "Kabupaten Serang", "kode_provinsi" => "36", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3671", "kab_kota" => "Kota Tangerang", "kode_provinsi" => "36", "is_ibu_kota" => 1, "aktif" => 1],
            ["kode_kab_kota" => "3672", "kab_kota" => "Kota Cilegon", "kode_provinsi" => "36", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3673", "kab_kota" => "Kota Serang", "kode_provinsi" => "36", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "3674", "kab_kota" => "Kota Tangerang Selatan", "kode_provinsi" => "36", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "5101", "kab_kota" => "Kabupaten Jembrana", "kode_provinsi" => "51", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "5102", "kab_kota" => "Kabupaten Tabanan", "kode_provinsi" => "51", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "5103", "kab_kota" => "Kabupaten Badung", "kode_provinsi" => "51", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "5104", "kab_kota" => "Kabupaten Gianyar", "kode_provinsi" => "51", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "5105", "kab_kota" => "Kabupaten Klungkung", "kode_provinsi" => "51", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "5106", "kab_kota" => "Kabupaten Bangli", "kode_provinsi" => "51", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "5107", "kab_kota" => "Kabupaten Karangasem", "kode_provinsi" => "51", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "5108", "kab_kota" => "Kabupaten Buleleng", "kode_provinsi" => "51", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "5171", "kab_kota" => "Kota Denpasar", "kode_provinsi" => "51", "is_ibu_kota" => 1, "aktif" => 1],
            ["kode_kab_kota" => "5201", "kab_kota" => "Kabupaten Lombok Barat", "kode_provinsi" => "52", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "5202", "kab_kota" => "Kabupaten Lombok Tengah", "kode_provinsi" => "52", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "5203", "kab_kota" => "Kabupaten Lombok Timur", "kode_provinsi" => "52", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "5204", "kab_kota" => "Kabupaten Sumbawa", "kode_provinsi" => "52", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "5205", "kab_kota" => "Kabupaten Dompu", "kode_provinsi" => "52", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "5206", "kab_kota" => "Kabupaten Bima", "kode_provinsi" => "52", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "5207", "kab_kota" => "Kabupaten Sumbawa Barat", "kode_provinsi" => "52", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "5208", "kab_kota" => "Kabupaten Lombok Utara", "kode_provinsi" => "52", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "5271", "kab_kota" => "Kota Mataram", "kode_provinsi" => "52", "is_ibu_kota" => 1, "aktif" => 1],
            ["kode_kab_kota" => "5272", "kab_kota" => "Kota Bima", "kode_provinsi" => "52", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "5301", "kab_kota" => "Kabupaten Kupang", "kode_provinsi" => "53", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "5302", "kab_kota" => "Kabupaten Timor Tengah Selatan", "kode_provinsi" => "53", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "5303", "kab_kota" => "Kabupaten Timor Tengah Utara", "kode_provinsi" => "53", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "5304", "kab_kota" => "Kabupaten Belu", "kode_provinsi" => "53", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "5305", "kab_kota" => "Kabupaten Alor", "kode_provinsi" => "53", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "5306", "kab_kota" => "Kabupaten Flores Timur", "kode_provinsi" => "53", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "5307", "kab_kota" => "Kabupaten Sikka", "kode_provinsi" => "53", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "5308", "kab_kota" => "Kabupaten Ende", "kode_provinsi" => "53", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "5309", "kab_kota" => "Kabupaten Ngada", "kode_provinsi" => "53", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "5310", "kab_kota" => "Kabupaten Manggarai", "kode_provinsi" => "53", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "5311", "kab_kota" => "Kabupaten Sumba Timur", "kode_provinsi" => "53", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "5312", "kab_kota" => "Kabupaten Sumba Barat", "kode_provinsi" => "53", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "5313", "kab_kota" => "Kabupaten Lembata", "kode_provinsi" => "53", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "5314", "kab_kota" => "Kabupaten Rote Ndao", "kode_provinsi" => "53", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "5315", "kab_kota" => "Kabupaten Manggarai Barat", "kode_provinsi" => "53", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "5316", "kab_kota" => "Kabupaten Nagekeo", "kode_provinsi" => "53", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "5317", "kab_kota" => "Kabupaten Sumba Tengah", "kode_provinsi" => "53", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "5318", "kab_kota" => "Kabupaten Sumba Barat Daya", "kode_provinsi" => "53", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "5319", "kab_kota" => "Kabupaten Manggarai Timur", "kode_provinsi" => "53", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "5320", "kab_kota" => "Kabupaten Sabu Raijua", "kode_provinsi" => "53", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "5321", "kab_kota" => "Kabupaten Malaka", "kode_provinsi" => "53", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "5371", "kab_kota" => "Kota Kupang", "kode_provinsi" => "53", "is_ibu_kota" => 1, "aktif" => 1],
            ["kode_kab_kota" => "6101", "kab_kota" => "Kabupaten Sambas", "kode_provinsi" => "61", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "6102", "kab_kota" => "Kabupaten Mempawah", "kode_provinsi" => "61", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "6103", "kab_kota" => "Kabupaten Sanggau", "kode_provinsi" => "61", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "6104", "kab_kota" => "Kabupaten Ketapang", "kode_provinsi" => "61", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "6105", "kab_kota" => "Kabupaten Sintang", "kode_provinsi" => "61", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "6106", "kab_kota" => "Kabupaten Kapuas Hulu", "kode_provinsi" => "61", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "6107", "kab_kota" => "Kabupaten Bengkayang", "kode_provinsi" => "61", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "6108", "kab_kota" => "Kabupaten Landak", "kode_provinsi" => "61", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "6109", "kab_kota" => "Kabupaten Sekadau", "kode_provinsi" => "61", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "6110", "kab_kota" => "Kabupaten Melawi", "kode_provinsi" => "61", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "6111", "kab_kota" => "Kabupaten Kayong Utara", "kode_provinsi" => "61", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "6112", "kab_kota" => "Kabupaten Kubu Raya", "kode_provinsi" => "61", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "6171", "kab_kota" => "Kota Pontianak", "kode_provinsi" => "61", "is_ibu_kota" => 1, "aktif" => 1],
            ["kode_kab_kota" => "6172", "kab_kota" => "Kota Singkawang", "kode_provinsi" => "61", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "6201", "kab_kota" => "Kabupaten Kotawaringin Barat", "kode_provinsi" => "62", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "6202", "kab_kota" => "Kabupaten Kotawaringin Timur", "kode_provinsi" => "62", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "6203", "kab_kota" => "Kabupaten Kapuas", "kode_provinsi" => "62", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "6204", "kab_kota" => "Kabupaten Barito Selatan", "kode_provinsi" => "62", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "6205", "kab_kota" => "Kabupaten Barito Utara", "kode_provinsi" => "62", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "6206", "kab_kota" => "Kabupaten Katingan", "kode_provinsi" => "62", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "6207", "kab_kota" => "Kabupaten Seruyan", "kode_provinsi" => "62", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "6208", "kab_kota" => "Kabupaten Sukamara", "kode_provinsi" => "62", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "6209", "kab_kota" => "Kabupaten Lamandau", "kode_provinsi" => "62", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "6210", "kab_kota" => "Kabupaten Gunung Mas", "kode_provinsi" => "62", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "6211", "kab_kota" => "Kabupaten Pulang Pisau", "kode_provinsi" => "62", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "6212", "kab_kota" => "Kabupaten Murung Raya", "kode_provinsi" => "62", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "6213", "kab_kota" => "Kabupaten Barito Timur", "kode_provinsi" => "62", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "6271", "kab_kota" => "Kota Palangkaraya", "kode_provinsi" => "62", "is_ibu_kota" => 1, "aktif" => 1],
            ["kode_kab_kota" => "6301", "kab_kota" => "Kabupaten Tanah Laut", "kode_provinsi" => "63", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "6302", "kab_kota" => "Kabupaten Kotabaru", "kode_provinsi" => "63", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "6303", "kab_kota" => "Kabupaten Banjar", "kode_provinsi" => "63", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "6304", "kab_kota" => "Kabupaten Barito Kuala", "kode_provinsi" => "63", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "6305", "kab_kota" => "Kabupaten Tapin", "kode_provinsi" => "63", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "6306", "kab_kota" => "Kabupaten Hulu Sungai Selatan", "kode_provinsi" => "63", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "6307", "kab_kota" => "Kabupaten Hulu Sungai Tengah", "kode_provinsi" => "63", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "6308", "kab_kota" => "Kabupaten Hulu Sungai Utara", "kode_provinsi" => "63", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "6309", "kab_kota" => "Kabupaten Tabalong", "kode_provinsi" => "63", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "6310", "kab_kota" => "Kabupaten Tanah Bumbu", "kode_provinsi" => "63", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "6311", "kab_kota" => "Kabupaten Balangan", "kode_provinsi" => "63", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "6371", "kab_kota" => "Kota Banjarmasin", "kode_provinsi" => "63", "is_ibu_kota" => 1, "aktif" => 1],
            ["kode_kab_kota" => "6372", "kab_kota" => "Kota Banjarbaru", "kode_provinsi" => "63", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "6401", "kab_kota" => "Kabupaten Paser", "kode_provinsi" => "64", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "6402", "kab_kota" => "Kabupaten Kutai Kartanegara", "kode_provinsi" => "64", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "6403", "kab_kota" => "Kabupaten Berau", "kode_provinsi" => "64", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "6407", "kab_kota" => "Kabupaten Kutai Barat", "kode_provinsi" => "64", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "6408", "kab_kota" => "Kabupaten Kutai Timur", "kode_provinsi" => "64", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "6409", "kab_kota" => "Kabupaten Penajam Paser Utara", "kode_provinsi" => "64", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "6411", "kab_kota" => "Kabupaten Mahakam Ulu", "kode_provinsi" => "64", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "6471", "kab_kota" => "Kota Balikpapan", "kode_provinsi" => "64", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "6472", "kab_kota" => "Kota Samarinda", "kode_provinsi" => "64", "is_ibu_kota" => 1, "aktif" => 1],
            ["kode_kab_kota" => "6474", "kab_kota" => "Kota Bontang", "kode_provinsi" => "64", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "6501", "kab_kota" => "Kabupaten Bulungan", "kode_provinsi" => "65", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "6502", "kab_kota" => "Kabupaten Malinau", "kode_provinsi" => "65", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "6503", "kab_kota" => "Kabupaten Nunukan", "kode_provinsi" => "65", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "6504", "kab_kota" => "Kabupaten Tana Tidung", "kode_provinsi" => "65", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "6571", "kab_kota" => "Kota Tarakan", "kode_provinsi" => "65", "is_ibu_kota" => 1, "aktif" => 1],
            ["kode_kab_kota" => "7101", "kab_kota" => "Kabupaten Bolaang Mongondow", "kode_provinsi" => "71", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "7102", "kab_kota" => "Kabupaten Minahasa", "kode_provinsi" => "71", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "7103", "kab_kota" => "Kabupaten Kepulauan Sangihe", "kode_provinsi" => "71", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "7104", "kab_kota" => "Kabupaten Kepulauan Talaud", "kode_provinsi" => "71", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "7105", "kab_kota" => "Kabupaten Minahasa Selatan", "kode_provinsi" => "71", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "7106", "kab_kota" => "Kabupaten Minahasa Utara", "kode_provinsi" => "71", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "7107", "kab_kota" => "Kabupaten Minahasa Tenggara", "kode_provinsi" => "71", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "7108", "kab_kota" => "Kabupaten Bolaang Mongondow Utara", "kode_provinsi" => "71", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "7109", "kab_kota" => "Kabupaten Kepulauan Siau Tagulandangbiaro", "kode_provinsi" => "71", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "7110", "kab_kota" => "Kabupaten Bolaang Mongondow Timur", "kode_provinsi" => "71", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "7111", "kab_kota" => "Kabupaten Bolaang Mongondow Selatan", "kode_provinsi" => "71", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "7171", "kab_kota" => "Kota Manado", "kode_provinsi" => "71", "is_ibu_kota" => 1, "aktif" => 1],
            ["kode_kab_kota" => "7172", "kab_kota" => "Kota Bitung", "kode_provinsi" => "71", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "7173", "kab_kota" => "Kota Tomohon", "kode_provinsi" => "71", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "7174", "kab_kota" => "Kota Kotamobagu", "kode_provinsi" => "71", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "7201", "kab_kota" => "Kabupaten Banggai", "kode_provinsi" => "72", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "7202", "kab_kota" => "Kabupaten Poso", "kode_provinsi" => "72", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "7203", "kab_kota" => "Kabupaten Donggala", "kode_provinsi" => "72", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "7204", "kab_kota" => "Kabupaten Toli Toli", "kode_provinsi" => "72", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "7205", "kab_kota" => "Kabupaten Buol", "kode_provinsi" => "72", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "7206", "kab_kota" => "Kabupaten Morowali", "kode_provinsi" => "72", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "7207", "kab_kota" => "Kabupaten Banggai Kepulauan", "kode_provinsi" => "72", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "7208", "kab_kota" => "Kabupaten Parigi Moutong", "kode_provinsi" => "72", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "7209", "kab_kota" => "Kabupaten Tojo Una Una", "kode_provinsi" => "72", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "7210", "kab_kota" => "Kabupaten Sigi", "kode_provinsi" => "72", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "7211", "kab_kota" => "Kabupaten Banggai Laut", "kode_provinsi" => "72", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "7212", "kab_kota" => "Kabupaten Morowali Utara", "kode_provinsi" => "72", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "7271", "kab_kota" => "Kota Palu", "kode_provinsi" => "72", "is_ibu_kota" => 1, "aktif" => 1],
            ["kode_kab_kota" => "7301", "kab_kota" => "Kabupaten Kepulauan Selayar", "kode_provinsi" => "73", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "7302", "kab_kota" => "Kabupaten Bulukumba", "kode_provinsi" => "73", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "7303", "kab_kota" => "Kabupaten Bantaeng", "kode_provinsi" => "73", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "7304", "kab_kota" => "Kabupaten Jeneponto", "kode_provinsi" => "73", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "7305", "kab_kota" => "Kabupaten Takalar", "kode_provinsi" => "73", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "7306", "kab_kota" => "Kabupaten Gowa", "kode_provinsi" => "73", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "7307", "kab_kota" => "Kabupaten Sinjai", "kode_provinsi" => "73", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "7308", "kab_kota" => "Kabupaten Bone", "kode_provinsi" => "73", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "7309", "kab_kota" => "Kabupaten Maros", "kode_provinsi" => "73", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "7310", "kab_kota" => "Kabupaten Pangkajene Kepulauan", "kode_provinsi" => "73", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "7311", "kab_kota" => "Kabupaten Barru", "kode_provinsi" => "73", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "7312", "kab_kota" => "Kabupaten Soppeng", "kode_provinsi" => "73", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "7313", "kab_kota" => "Kabupaten Wajo", "kode_provinsi" => "73", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "7314", "kab_kota" => "Kabupaten Sidenreng Rappang", "kode_provinsi" => "73", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "7315", "kab_kota" => "Kabupaten Pinrang", "kode_provinsi" => "73", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "7316", "kab_kota" => "Kabupaten Enrekang", "kode_provinsi" => "73", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "7317", "kab_kota" => "Kabupaten Luwu", "kode_provinsi" => "73", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "7318", "kab_kota" => "Kabupaten Tana Toraja", "kode_provinsi" => "73", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "7322", "kab_kota" => "Kabupaten Luwu Utara", "kode_provinsi" => "73", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "7324", "kab_kota" => "Kabupaten Luwu Timur", "kode_provinsi" => "73", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "7326", "kab_kota" => "Kabupaten Toraja Utara", "kode_provinsi" => "73", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "7371", "kab_kota" => "Kota Makassar", "kode_provinsi" => "73", "is_ibu_kota" => 1, "aktif" => 1],
            ["kode_kab_kota" => "7372", "kab_kota" => "Kota Pare Pare", "kode_provinsi" => "73", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "7373", "kab_kota" => "Kota Palopo", "kode_provinsi" => "73", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "7401", "kab_kota" => "Kabupaten Kolaka", "kode_provinsi" => "74", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "7402", "kab_kota" => "Kabupaten Konawe", "kode_provinsi" => "74", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "7403", "kab_kota" => "Kabupaten Muna", "kode_provinsi" => "74", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "7404", "kab_kota" => "Kabupaten Buton", "kode_provinsi" => "74", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "7405", "kab_kota" => "Kabupaten Konawe Selatan", "kode_provinsi" => "74", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "7406", "kab_kota" => "Kabupaten Bombana", "kode_provinsi" => "74", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "7407", "kab_kota" => "Kabupaten Wakatobi", "kode_provinsi" => "74", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "7408", "kab_kota" => "Kabupaten Kolaka Utara", "kode_provinsi" => "74", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "7409", "kab_kota" => "Kabupaten Konawe Utara", "kode_provinsi" => "74", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "7410", "kab_kota" => "Kabupaten Buton Utara", "kode_provinsi" => "74", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "7411", "kab_kota" => "Kabupaten Kolaka Timur", "kode_provinsi" => "74", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "7412", "kab_kota" => "Kabupaten Konawe Kepulauan", "kode_provinsi" => "74", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "7413", "kab_kota" => "Kabupaten Muna Barat", "kode_provinsi" => "74", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "7414", "kab_kota" => "Kabupaten Buton Tengah", "kode_provinsi" => "74", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "7415", "kab_kota" => "Kabupaten Buton Selatan", "kode_provinsi" => "74", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "7471", "kab_kota" => "Kota Kendari", "kode_provinsi" => "74", "is_ibu_kota" => 1, "aktif" => 1],
            ["kode_kab_kota" => "7472", "kab_kota" => "Kota Bau Bau", "kode_provinsi" => "74", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "7501", "kab_kota" => "Kabupaten Gorontalo", "kode_provinsi" => "75", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "7502", "kab_kota" => "Kabupaten Boalemo", "kode_provinsi" => "75", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "7503", "kab_kota" => "Kabupaten Bone Bolango", "kode_provinsi" => "75", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "7504", "kab_kota" => "Kabupaten Pahuwato", "kode_provinsi" => "75", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "7505", "kab_kota" => "Kabupaten Gorontalo Utara", "kode_provinsi" => "75", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "7571", "kab_kota" => "Kota Gorontalo", "kode_provinsi" => "75", "is_ibu_kota" => 1, "aktif" => 1],
            ["kode_kab_kota" => "7601", "kab_kota" => "Kabupaten Pasangkayu", "kode_provinsi" => "76", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "7602", "kab_kota" => "Kabupaten Mamuju", "kode_provinsi" => "76", "is_ibu_kota" => 1, "aktif" => 1],
            ["kode_kab_kota" => "7603", "kab_kota" => "Kabupaten Mamasa", "kode_provinsi" => "76", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "7604", "kab_kota" => "Kabupaten Polewali Mandar", "kode_provinsi" => "76", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "7605", "kab_kota" => "Kabupaten Majene", "kode_provinsi" => "76", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "7606", "kab_kota" => "Kabupaten Mamuju Tengah", "kode_provinsi" => "76", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "8101", "kab_kota" => "Kabupaten Maluku Tengah", "kode_provinsi" => "81", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "8102", "kab_kota" => "Kabupaten Maluku Tenggara", "kode_provinsi" => "81", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "8103", "kab_kota" => "Kabupaten Kepulauan Tanimbar", "kode_provinsi" => "81", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "8104", "kab_kota" => "Kabupaten Buru", "kode_provinsi" => "81", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "8105", "kab_kota" => "Kabupaten Seram Bagian Timur", "kode_provinsi" => "81", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "8106", "kab_kota" => "Kabupaten Seram Bagian Barat", "kode_provinsi" => "81", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "8107", "kab_kota" => "Kabupaten Kepulauan Aru", "kode_provinsi" => "81", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "8108", "kab_kota" => "Kabupaten Maluku Barat Daya", "kode_provinsi" => "81", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "8109", "kab_kota" => "Kabupaten Buru Selatan", "kode_provinsi" => "81", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "8171", "kab_kota" => "Kota Ambon", "kode_provinsi" => "81", "is_ibu_kota" => 1, "aktif" => 1],
            ["kode_kab_kota" => "8172", "kab_kota" => "Kota Tual", "kode_provinsi" => "81", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "8201", "kab_kota" => "Kabupaten Halmahera Barat", "kode_provinsi" => "82", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "8202", "kab_kota" => "Kabupaten Halmahera Tengah", "kode_provinsi" => "82", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "8203", "kab_kota" => "Kabupaten Halmahera Utara", "kode_provinsi" => "82", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "8204", "kab_kota" => "Kabupaten Halmahera Selatan", "kode_provinsi" => "82", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "8205", "kab_kota" => "Kabupaten Kepulauan Sula", "kode_provinsi" => "82", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "8206", "kab_kota" => "Kabupaten Halmahera Timur", "kode_provinsi" => "82", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "8207", "kab_kota" => "Kabupaten Pulau Morotai", "kode_provinsi" => "82", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "8208", "kab_kota" => "Kabupaten Pulau Taliabu", "kode_provinsi" => "82", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "8271", "kab_kota" => "Kota Ternate", "kode_provinsi" => "82", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "8272", "kab_kota" => "Kota Tidore Kepulauan", "kode_provinsi" => "82", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "9101", "kab_kota" => "Kabupaten Merauke", "kode_provinsi" => "91", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "9102", "kab_kota" => "Kabupaten Jayawijaya", "kode_provinsi" => "91", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "9103", "kab_kota" => "Kabupaten Jayapura", "kode_provinsi" => "91", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "9104", "kab_kota" => "Kabupaten Nabire", "kode_provinsi" => "91", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "9105", "kab_kota" => "Kabupaten Kepulauan Yapen", "kode_provinsi" => "91", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "9106", "kab_kota" => "Kabupaten Biak Numfor", "kode_provinsi" => "91", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "9107", "kab_kota" => "Kabupaten Puncak Jaya", "kode_provinsi" => "91", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "9108", "kab_kota" => "Kabupaten Paniai", "kode_provinsi" => "91", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "9109", "kab_kota" => "Kabupaten Mimika", "kode_provinsi" => "91", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "9110", "kab_kota" => "Kabupaten Sarmi", "kode_provinsi" => "91", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "9111", "kab_kota" => "Kabupaten Keerom", "kode_provinsi" => "91", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "9112", "kab_kota" => "Kabupaten Pegunungan Bintang", "kode_provinsi" => "91", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "9113", "kab_kota" => "Kabupaten Yahukimo", "kode_provinsi" => "91", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "9114", "kab_kota" => "Kabupaten Tolikara", "kode_provinsi" => "91", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "9115", "kab_kota" => "Kabupaten Waropen", "kode_provinsi" => "91", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "9116", "kab_kota" => "Kabupaten Boven Digoel", "kode_provinsi" => "91", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "9117", "kab_kota" => "Kabupaten Mappi", "kode_provinsi" => "91", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "9118", "kab_kota" => "Kabupaten Asmat", "kode_provinsi" => "91", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "9119", "kab_kota" => "Kabupaten Supiori", "kode_provinsi" => "91", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "9120", "kab_kota" => "Kabupaten Mamberamo Raya", "kode_provinsi" => "91", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "9121", "kab_kota" => "Kabupaten Mamberamo Tengah", "kode_provinsi" => "91", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "9122", "kab_kota" => "Kabupaten Yalimo", "kode_provinsi" => "91", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "9123", "kab_kota" => "Kabupaten Lanny Jaya", "kode_provinsi" => "91", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "9124", "kab_kota" => "Kabupaten Nduga", "kode_provinsi" => "91", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "9125", "kab_kota" => "Kabupaten Puncak", "kode_provinsi" => "91", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "9126", "kab_kota" => "Kabupaten Dogiyai", "kode_provinsi" => "91", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "9127", "kab_kota" => "Kabupaten Intan Jaya", "kode_provinsi" => "91", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "9128", "kab_kota" => "Kabupaten Deiyai", "kode_provinsi" => "91", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "9171", "kab_kota" => "Kota Jayapura", "kode_provinsi" => "91", "is_ibu_kota" => 1, "aktif" => 1],
            ["kode_kab_kota" => "9201", "kab_kota" => "Kabupaten Sorong", "kode_provinsi" => "92", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "9202", "kab_kota" => "Kabupaten Manokwari", "kode_provinsi" => "92", "is_ibu_kota" => 1, "aktif" => 1],
            ["kode_kab_kota" => "9203", "kab_kota" => "Kabupaten Fak Fak", "kode_provinsi" => "92", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "9204", "kab_kota" => "Kabupaten Sorong Selatan", "kode_provinsi" => "92", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "9205", "kab_kota" => "Kabupaten Raja Ampat", "kode_provinsi" => "92", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "9206", "kab_kota" => "Kabupaten Teluk Bintuni", "kode_provinsi" => "92", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "9207", "kab_kota" => "Kabupaten Teluk Wondama", "kode_provinsi" => "92", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "9208", "kab_kota" => "Kabupaten Kaimana", "kode_provinsi" => "92", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "9209", "kab_kota" => "Kabupaten Tambrauw", "kode_provinsi" => "92", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "9210", "kab_kota" => "Kabupaten Maybrat", "kode_provinsi" => "92", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "9211", "kab_kota" => "Kabupaten Manokwari Selatan", "kode_provinsi" => "92", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "9212", "kab_kota" => "Kabupaten Pegunungan Arfak", "kode_provinsi" => "92", "is_ibu_kota" => 0, "aktif" => 1],
            ["kode_kab_kota" => "9271", "kab_kota" => "Kota Sorong", "kode_provinsi" => "92", "is_ibu_kota" => 0, "aktif" => 1],            
        ]);
    }
}
